name: Snyk Scan
# testing sample DevOps with Git workflow
on:
  push:
    branches:
      - master  # Modify this to match your repository's main branch
  pull_request:
    branches: [ "master" ]    

 

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk now
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Add your Snyk token to GitHub Secrets
        run: snyk auth $SNYK_TOKEN


      - name: Run Snyk test
        run: snyk test 

      - name: Run Snyk monitor
        run: snyk monitor
