name: GitLeaks Scan
# testing sample DevOps with Git workflow
on:
  push:
    branches:
      - master  # Modify this to match your repository's main branch
  pull_request:
    branches: [ "master" ]    

 

jobs:
  gitleaks:
    runs-on: ubuntu-latest

 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

 

    - name: Install GitLeaks
      run: |
        wget -q -O gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
        ls -l
        tar -xzvf gitleaks.tar.gz
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/

 

    - name: Run GitLeaks
      run: |
        gitleaks detect --redact

  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
         java-version: 17

      - name: Set up Node 14
        uses: actions/setup-node@v3
        with:
         node-version: 14


     
      - name: Authenticate Snyk now
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Add your Snyk token to GitHub Secrets
        run: snyk auth $SNYK_TOKEN


      - name: Run Snyk test
        run: snyk test 

      - name: Run Snyk monitor
        run: snyk monitor
